sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kY9eO657E2gMCZ3PhNEajxyPRVV2rmqU7o98xCJ66SDQra3TfGWv8GIkeybQB/uage5ogd9tvbdlOIyKbW/e53pXCI/njrx7dC31Fkp8w1subahAEyn1M08QURT69FmoYhwCaPt9nC/wjWEpINfgRlw/wM5ms+eeEAVJRYiApLWVNpDzZjQIMewXqCuA2W9CnauyOPPYmvSmSJ1UfPsNRSBftcC5LRpOxBBTGQgQ1qZBxEZzarnvn+O6VxowbjLa5PPYE4K7s72Gw003n0ZSNkMW9cjnB8aKIkQLed55693EQwWG/99OobzNN2uctpu7461CYDs07cBj0IYbHpcgJgVfSukJeWAvQS0V55amATZTBN9OTNIf0qGV87qAHaXX3DTJdd1ZBkiypeAV2fq9SznRbI9pW/yT3ggYC5CunWT9EWMAzjypI3m6bTrAYpu7SnaBqxSE/IpNeWq04C/h0WYVPG7sdV1suP5WL3XcCK5d6Wpn7fUHJOgALrjeAn59Rjjx/Ks1ZNyh3cTA1gVduaCLh9CvtwDlXpNYDWH+bqct+8Ac7ro26qjocKQibwtBAfdKz2QGaLfBzkvYTPgy2kFrSCFKoysIE/kvFiSAtvhcwGFwricUqglYJm0u1SfrDIIZzBpwCrdPfd/W77TcO7s4WbNRjw0rZjqqASG77v8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cosmopolis-Volume-2_3964
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy